#!/usr/bin/env python3
"""
tools/gen_sos.py — offline Butterworth SOS coefficient generator

Usage:
    python tools/gen_sos.py src/biquad_coeffs.h     # writes file directly (recommended)
    python tools/gen_sos.py > src/biquad_coeffs.h    # POSIX stdout redirect

Generates a C header with float32 SOS arrays for two bandpass filters:
    Breathing  0.1–0.6 Hz, 4th order
    Heart      0.8–3.0 Hz, 4th order
at fs = CSI_FS = 100 Hz.

Each 4th-order bandpass produces 4 second-order sections (8 poles / 2).
Section format: [b0, b1, b2, 1.0, a1, a2]  (scipy 'sos' layout, a0 normalised).

After generation, paste main/biquad_coeffs.h into the firmware tree and rebuild.
Filter constants can be replaced any time without changing the wire format or
Redis schema (only the C header + rebuild required).
"""

import sys

try:
    from scipy.signal import butter
    import numpy as np
except ImportError:
    sys.exit("ERROR: scipy and numpy required — pip install scipy numpy")

# ─── Parameters (must match config.h) ────────────────────────────────────────
FS          = 100           # Hz  (CSI_FS)
ORDER       = 4             # Butterworth prototype order → 4 SOS sections (bandpass)
RESP_BAND   = [0.1, 0.6]   # Hz
HEART_BAND  = [0.8, 3.0]   # Hz


def compute_sos(band, fs, order):
    nyq = fs / 2.0
    sos = butter(order, [b / nyq for b in band], btype='bandpass', output='sos')
    # scipy guarantees a0=1; verify
    assert np.allclose(sos[:, 3], 1.0), "a0 normalisation violated"
    return sos


def fmt_array(name, desc, sos):
    n = sos.shape[0]
    lines = []
    lines.append(f"/* {desc} - [b0,b1,b2, 1,a1,a2] per section */")
    lines.append(f"static const float {name}[SOS_N_SECTIONS][6] = {{")
    for i, sec in enumerate(sos):
        b0, b1, b2, _, a1, a2 = sec
        lines.append(
            f"    /* s{i} */ {{"
            f" {b0:+.10e}f, {b1:+.10e}f, {b2:+.10e}f,"
            f" 1.0f, {a1:+.10e}f, {a2:+.10e}f }},"
        )
    lines.append("};")
    return "\n".join(lines)


def main():
    resp_sos  = compute_sos(RESP_BAND,  FS, ORDER)
    heart_sos = compute_sos(HEART_BAND, FS, ORDER)

    n_sections = resp_sos.shape[0]
    assert n_sections == heart_sos.shape[0], "section count mismatch"

    out = []
    out.append("/* AUTO-GENERATED by tools/gen_sos.py - do not edit manually */")
    out.append(f"/* fs={FS} Hz | order={ORDER} Butterworth bandpass | {n_sections} SOS sections */")
    out.append(f"/* Breathing {RESP_BAND[0]}-{RESP_BAND[1]} Hz  |  Heart {HEART_BAND[0]}-{HEART_BAND[1]} Hz */")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append(f"#define SOS_N_SECTIONS  {n_sections}")
    out.append("")
    out.append(fmt_array("g_sos_resp",  f"Breathing {RESP_BAND[0]}-{RESP_BAND[1]} Hz", resp_sos))
    out.append("")
    out.append(fmt_array("g_sos_heart", f"Heart {HEART_BAND[0]}-{HEART_BAND[1]} Hz", heart_sos))
    out.append("")

    text = "\n".join(out)
    # Output is pure ASCII. Write the file directly when a path arg is given
    # (avoids PowerShell `>` emitting UTF-16); otherwise print to stdout.
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w", encoding="ascii", newline="\n") as f:
            f.write(text + "\n")
        sys.stderr.write(f"wrote {sys.argv[1]}\n")
    else:
        print(text)


if __name__ == "__main__":
    main()
