/* AUTO-GENERATED by tools/gen_sos.py — do not edit manually              */
/* !!! PLACEHOLDER — filter output is ZERO until regenerated !!!           */
/*                                                                          */
/*   pip install scipy numpy                                                */
/*   python tools/gen_sos.py > src/biquad_coeffs.h                         */
/*                                                                          */
/* fs=100 Hz | order=4 Butterworth bandpass | 4 SOS sections               */
/* Breathing 0.1–0.6 Hz  |  Heart 0.8–3.0 Hz                              */

#pragma once

#define SOS_N_SECTIONS  4

/* Breathing 0.1–0.6 Hz: [b0, b1, b2, 1, a1, a2] per section */
static const float g_sos_resp[SOS_N_SECTIONS][6] = {
    /* s0 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
    /* s1 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
    /* s2 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
    /* s3 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
};

/* Heart 0.8–3.0 Hz: [b0, b1, b2, 1, a1, a2] per section */
static const float g_sos_heart[SOS_N_SECTIONS][6] = {
    /* s0 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
    /* s1 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
    /* s2 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
    /* s3 */ { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f },
};
